# Generated by Django 6.0 on 2025-12-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
