# Generated by Django 6.0 on 2025-12-16 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_alter_farmerprofile_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='farmers.farmerprofile'),
        ),
    ]
